filebeat.inputs:
  - type: log
    enabled: true
    paths:
     # - /usr/share/filebeat/logs/*.log  # Path inside the container
       - /usr/share/filebeat/data/sample.csv
output.logstash:
  hosts: ["logstash:5044"]  # Send logs to Logstash
  # ssl:
  #   verification_mode: "none"  # Disable SSL verification (optional)

# setup.template.enabled: true
# setup.kibana:
#   host: "http://kibana:5601"  # Optional if using Kibana

# processors:
#   - add_host_metadata: ~
#   - add_cloud_metadata: ~
#   - add_docker_metadata: ~
#   - add_kubernetes_metadata: ~
