cluster.name: es-cluster
node.name: es-master
node.roles: [ master, remote_cluster_client ]

# Memory settings
bootstrap.memory_lock: true

# Network settings
network.host: 0.0.0.0

# Discovery settings for multi-node setup
discovery.seed_hosts: [ "es-worker-1", "es-worker-2" ]
cluster.initial_master_nodes: [ "es-master" ]

# Disable security (no SSL)
xpack.security.enabled: false
xpack.monitoring.collection.enabled: true

#xpack.remote_cluster.enabled: true
