- module: elasticsearch
  xpack.enabled: true
  hosts: ["http://es-master:9200", "http://es-worker-1:9200", "http://es-worker-2:9200"]
  # username: "elastic"
  #  password: "changeme"
  period: 10s
  enabled: true

